### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by enzofrnt** [Horou/djangorestframework-deepserializer#1]
Dans le readme, il est demandé d'utiliser `get_serializer()` sur une Class qui hérite de `deepserializer`.
Mais ça ne fonctionne pas :
type object 'SbomsSerializer' has no attribute 'get_serializer'

**Comment by Horou** [comment]
c'est vrais, la fonction c'est get_serializer_class() maintenant, je corrige le README

**Comment by enzofrnt** [comment]
Super merci

**Comment by Horou** [comment]
pour l'explication c'est: Les Viewset on naturellement une fonction get_serializer() qui renvoie une instance de class du sérialiser, et une fonction get_serializer_class() qui renvoie une class de sérialiser. Donc pour une question de cohérence pour la class DeepSerializer, j'ai renommé la fonction get_serializer en get_serializer_class car c'est une fonction qui renvoie une class, et non une instance de class.
