### ISSUE TITLE
Add a default `deep_update_or_create` in viewset

### ISSUE THREAD

**Issue by enzofrnt** [Horou/djangorestframework-deepserializer#7]
Pour rendre le développement encore plus simple, pourquoi par défaut permettre l'utilisation du `deep_update_or_create` avec une gestion d'erreur pertinente comme dans l'exemple du readme ?

**Comment by Horou** [comment]
C'est par sécurité, si je rajoute cette fonction a DeepViewSet, toute les viewset auront un point d'accès pour modifié n'importe quelle autre model. Pour moi le deep_update_or_create doit être utilisé dans une seul viewset qui vas connecté tout les model a modifié. Le read_me est un peut vieux mais tu peut écrire la fonction qui vas appelé deep_update_or_create comme ça:
```
class SeriesViewSet(DeepViewSet):
    queryset = Series.objects

    @action(detail=False, methods=['post'])
    def deep_create(self, request):
        serializer = self.get_serializer()
        results = serializer.deep_update_or_create(self.queryset.model, request.data, raise_exception=True)
        return Response(results, status=status.HTTP_201_CREATED)

```
fonctionne pour list ou dict sans rien changé

**Comment by enzofrnt** [comment]
c'est en effet un choix pertinent.
Mais cela devrait être expliqué dans la documentation, et je pense que c'est un défaut de conception, de ne pas être capable d'utiliser facilement le deep create.
Selon moi, il faut trouver une solution pour rendre ça possible et facilement.

**Comment by Horou** [comment]
j'ai rajouté la classe DeepCreateViewSet avec l'action deep_create qui va s'occuper de ça.

**Comment by enzofrnt** [comment]
Une ViewSet n'est pas une ModelViewSet.
