### ISSUE TITLE
Issue while create new objects in DB

### ISSUE THREAD

**Issue by enzofrnt** [Horou/djangorestframework-deepserializer#8]
Lorsque de créer un objet en base de données avec un `deep_update_or_create` il semble que la deepview ne se mette pas à jour avant que le serveur ne soit redémarré, car le nouvel objet n'apparaît pas lors d'un get. 
Par contre, sur un autre endpoint qui n'utilise pas deepview les nouveaux objets apparaisse.

Je push mon exemple dans lequel je retrouve l'erreur sur une branche pour que tu puisses regarder.

**Comment by Horou** [comment]
c'est parce-que tu a écrit:

class sudentview(DeepViewSet):
    serializer_class = studentserializer
    queryset = Student.objects.all()

au lieu de:

class sudentview(DeepViewSet):
    serializer_class = studentserializer
    queryset = Student.objects

le '.all()' va récupérer tous les éléments du queryset une seule fois, donc si tu met all dans une class comme la, il te donnera uniquement les élément qu'il a trouvé aux chargement de la class, il vaut mieux écrire all dans la fonction get_queryset car cette fonction est appelé plusieurs fois.
